language: ruby

before_script: "./script/ci/before.sh"

rvm:
  - 1.9.2

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare spec --trace

notifications:
  email:
    - jeremyleesmith@gmail.com
