development:
  adapter: sqlite3
  pool: 5
  database: db/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  database: <%= ENV['DB'] == 'sqlite' ? '\":memory:\"' : 'db/test.sqlite3' %>
  timeout: 500
